# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b6cdf3c2da98ee3664f9a56e350508edd1db12c8bcacc55ca9faa8b336d79b4c85defc0d808edabfb61d89276dcfb9cd917ddd101acb2fd5bfcb1c91727ead8

test:
  secret_key_base: e6713bc003649f5bcb6a5cb2bb97081e49b057527a27c1d7e8162fbf5dd34b87a90a8016eefb4f26a7ba57633e009b712eaba2173ff1e3e66832793c04c4bb0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
